rm not needed parantheses and default values
pythonfoo/pythonfooLite pull request #6
Opened 2022-10-09 11:02 UTC by hwmrocker

Sind diese Änderungen auch gewünscht?

2022-10-15 16:24 UTC, YtvwlD requested changes

2022-10-15 16:24 UTC, YtvwlD commented on Level_08/generatoren.py
> -    for char in s:
Hm, das macht vielleicht mehr Sinn zu behalten?

2022-10-15 16:24 UTC, YtvwlD commented on Level_10/label.py
> -# coding: utf-8
:+1:

2022-10-16 06:19 UTC, hwmrocker commented on Level_08/generatoren.py
> -    for char in s:
ich habe das wieder reverted. ich denke, den generatoren teil kann man noch etwas ausbauen, ich werde da noch ein ticket zu aufmachen.

2025-11-13 17:29 UTC, merged